version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telcox
      MYSQL_USER: telcox
      MYSQL_PASSWORD: telcox
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql

  bss:
    build:
      context: .
      dockerfile: bss_mock/Dockerfile
    ports:
      - "8001:8001"

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      DATABASE_URL: mysql+pymysql://telcox:telcox@db:3306/telcox
      BSS_BASE_URL: http://bss:8001
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      bss:
        condition: service_started

volumes:
  dbdata:
